import Head from "next/head";

import ChessGame from "~widgets/Game";

import styles from "./Home.module.scss";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Chess</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.appHeader}>Chess</header>
      <main>
        <ChessGame />
      </main>
    </div>
  );
}
